table Dim_times
	lineageTag: b113d1f7-a614-4874-8d2d-9f6098519ac4

	column Time
		dataType: dateTime
		formatString: yyyy-mm-dd hh:mm
		lineageTag: cd45c4e0-a9b5-44eb-a28d-a14d2b120771
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 68cb66fd-ffed-4a54-8d13-e7dfc32445ef
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 8038669f-0b32-4843-871c-60ec09823600
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column YearLabel
		dataType: string
		lineageTag: 0708380a-f896-4352-91d3-fbc998025adf
		summarizeBy: none
		sourceColumn: YearLabel

		annotation SummarizationSetBy = Automatic

	column YearLabelShort
		dataType: string
		lineageTag: ac07d2a2-d3f8-46c5-b4a8-e2aaacfbcc6d
		summarizeBy: none
		sourceColumn: YearLabelShort

		annotation SummarizationSetBy = Automatic

	column QuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: df4abf18-8bf1-4708-827b-9d6aa77e6609
		summarizeBy: sum
		sourceColumn: QuarterNumber

		annotation SummarizationSetBy = Automatic

	column QuarterLabel
		dataType: string
		lineageTag: 6a752843-bd95-431b-a3d5-1c7364d8f94f
		summarizeBy: none
		sourceColumn: QuarterLabel

		annotation SummarizationSetBy = Automatic

	column QuarterLabelShort
		dataType: string
		lineageTag: e2363a60-8535-4e17-aae4-9e299e213ba3
		summarizeBy: none
		sourceColumn: QuarterLabelShort

		annotation SummarizationSetBy = Automatic

	column QuarterYearLabel
		dataType: string
		lineageTag: 161bb65e-3792-4e02-9003-c0d7902a4038
		summarizeBy: none
		sourceColumn: QuarterYearLabel

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 8bdce7f1-65e2-445c-9e75-d052725c6c94
		summarizeBy: sum
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 0cfab409-6000-45ac-841e-e87614b9164f
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column MonthNameShort
		dataType: string
		lineageTag: 8e3fe6c3-b223-41be-9784-f256208b2212
		summarizeBy: none
		sourceColumn: MonthNameShort

		annotation SummarizationSetBy = Automatic

	column MonthYearLabel
		dataType: string
		lineageTag: 3e352be8-e97c-403c-80b5-dde368fd3412
		summarizeBy: none
		sourceColumn: MonthYearLabel
		sortByColumn: MonthKey

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column WeekStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: f076d3e1-ae20-42d6-b100-2a34b7af774f
		summarizeBy: none
		sourceColumn: WeekStart

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekStartLabel
		dataType: string
		lineageTag: dc66d1ec-0016-422c-b441-ea9ae5fb61f8
		summarizeBy: none
		sourceColumn: WeekStartLabel

		annotation SummarizationSetBy = Automatic

	column WeekStartNumber
		dataType: int64
		formatString: 0
		lineageTag: 573306e4-490a-434e-98ff-30bea9b529b7
		summarizeBy: sum
		sourceColumn: WeekStartNumber

		annotation SummarizationSetBy = Automatic

	column WeekEnd
		dataType: dateTime
		formatString: Long Date
		lineageTag: 68739382-c588-4b2b-9f89-f943903947d6
		summarizeBy: none
		sourceColumn: WeekEnd

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WeekEndLabel
		dataType: string
		lineageTag: a7d6103a-7d8f-437c-b1c8-1db02f8409ac
		summarizeBy: none
		sourceColumn: WeekEndLabel

		annotation SummarizationSetBy = Automatic

	column WeekEndNumber
		dataType: int64
		formatString: 0
		lineageTag: f7ab2336-96fa-4812-991b-a10044597caf
		summarizeBy: sum
		sourceColumn: WeekEndNumber

		annotation SummarizationSetBy = Automatic

	column DayOfYearNumber
		dataType: int64
		formatString: 0
		lineageTag: 0daf94c2-2b58-4f96-957e-99c066a27a26
		summarizeBy: sum
		sourceColumn: DayOfYearNumber

		annotation SummarizationSetBy = Automatic

	column DayOfMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 936b90b9-fa9f-4f7e-a00c-a3a495a56ec2
		summarizeBy: sum
		sourceColumn: DayOfMonthNumber

		annotation SummarizationSetBy = Automatic

	column WeekdayNumberMonSun
		dataType: int64
		formatString: 0
		lineageTag: 1f94b0e3-a9a2-4184-a2c9-9f63604b2509
		summarizeBy: sum
		sourceColumn: WeekdayNumberMonSun

		annotation SummarizationSetBy = Automatic

	column WeekdayNumberSunMon
		dataType: int64
		formatString: 0
		lineageTag: c5cbdbc4-65b3-4b8e-913a-c0df027b3c42
		summarizeBy: sum
		sourceColumn: WeekdayNumberSunMon

		annotation SummarizationSetBy = Automatic

	column DateLabel
		dataType: string
		lineageTag: 9674ba12-a4c4-4550-a359-8d15e9e29128
		summarizeBy: none
		sourceColumn: DateLabel

		annotation SummarizationSetBy = Automatic

	column WeekdayName
		dataType: string
		lineageTag: 7fd8b146-ee96-4924-a517-e9c50f499c6b
		summarizeBy: none
		sourceColumn: WeekdayName

		annotation SummarizationSetBy = Automatic

	column WeekdayNameShort
		dataType: string
		lineageTag: 43cbbc6d-6c1d-4579-8bbe-35faec91fea0
		summarizeBy: none
		sourceColumn: WeekdayNameShort

		annotation SummarizationSetBy = Automatic

	column Hour
		dataType: int64
		formatString: 0
		lineageTag: ef4e081e-9ed0-45ea-bca0-c69edc0108ff
		summarizeBy: sum
		sourceColumn: Hour

		annotation SummarizationSetBy = Automatic

	column Minute
		dataType: int64
		formatString: 0
		lineageTag: 7dab6dc2-f70e-4897-815d-5a1f29696af9
		summarizeBy: sum
		sourceColumn: Minute

		annotation SummarizationSetBy = Automatic

	column HourLabel
		dataType: string
		lineageTag: 9cf85fe2-77be-45a7-b33e-0ae853d99f54
		summarizeBy: none
		sourceColumn: HourLabel

		annotation SummarizationSetBy = Automatic

	column MinuteLabel
		dataType: string
		lineageTag: bce6cf7e-bd93-4269-a0c8-8945a2fceb38
		summarizeBy: none
		sourceColumn: MinuteLabel

		annotation SummarizationSetBy = Automatic

	column HourMinuteLabel
		dataType: string
		lineageTag: f2364c3e-5638-4842-9d1f-8c69e627dfeb
		summarizeBy: none
		sourceColumn: HourMinuteLabel

		annotation SummarizationSetBy = Automatic

	column OperatingWindow
		dataType: string
		lineageTag: dc4335f5-ea18-43ee-bfaf-53f44cae5342
		summarizeBy: none
		sourceColumn: OperatingWindow

		annotation SummarizationSetBy = Automatic

	column FinYear
		dataType: int64
		formatString: 0
		lineageTag: 4078cee4-eeb2-473c-99f8-f785247410a9
		summarizeBy: sum
		sourceColumn: FinYear

		annotation SummarizationSetBy = Automatic

	column FinYearLabel
		dataType: string
		lineageTag: 991f62c3-2fd2-40bb-b71b-3bf1c966041e
		summarizeBy: none
		sourceColumn: FinYearLabel

		annotation SummarizationSetBy = Automatic

	column FinYearLabelShort
		dataType: string
		lineageTag: b1f82337-425b-4dd2-8daf-1e89519d6234
		summarizeBy: none
		sourceColumn: FinYearLabelShort

		annotation SummarizationSetBy = Automatic

	column FinQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: c0549ea7-60aa-480e-87f8-4cc46ce308ba
		summarizeBy: sum
		sourceColumn: FinQuarterNumber

		annotation SummarizationSetBy = Automatic

	column FinQuarterLabel
		dataType: string
		lineageTag: b445cfde-f70c-4de7-bc61-da3de5a3dd91
		summarizeBy: none
		sourceColumn: FinQuarterLabel

		annotation SummarizationSetBy = Automatic

	column FinQuarterLabelShort
		dataType: string
		lineageTag: e1bd62a1-4836-425d-903d-1532ec610717
		summarizeBy: none
		sourceColumn: FinQuarterLabelShort

		annotation SummarizationSetBy = Automatic

	column FinQuarterYearLabel
		dataType: string
		lineageTag: 2c7f382d-ac2e-4d92-a694-5bf65c3dfa25
		summarizeBy: none
		sourceColumn: FinQuarterYearLabel

		annotation SummarizationSetBy = Automatic

	column FinMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: bbade1d9-d38a-4a18-b579-7059dd8b0983
		summarizeBy: sum
		sourceColumn: FinMonthNumber

		annotation SummarizationSetBy = Automatic

	column QuarterKey
		dataType: string
		lineageTag: f73dbecc-ea4f-436d-8866-226e423ea33c
		summarizeBy: none
		sourceColumn: QuarterKey

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: string
		lineageTag: 1a6468ef-91a4-49c1-acf2-b38d32ababb6
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column WeekStartKey
		dataType: string
		lineageTag: 46ba7d6b-f7f6-4bfd-8a5b-ac690b5e460e
		summarizeBy: none
		sourceColumn: WeekStartKey

		annotation SummarizationSetBy = Automatic

	column WeekEndKey
		dataType: string
		lineageTag: 83b7b4ed-8b6a-454a-98b2-3a7d2001bc8d
		summarizeBy: none
		sourceColumn: WeekEndKey

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: string
		lineageTag: f5a97b59-b8c2-4fcd-a962-89c6e2b63024
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column HourKey
		dataType: string
		lineageTag: 9c541653-e69b-4bf5-ac26-a5e756a8591b
		summarizeBy: none
		sourceColumn: HourKey

		annotation SummarizationSetBy = Automatic

	column MinuteKey
		dataType: string
		lineageTag: 2cb6c774-2ed0-43d6-9404-7f37bd6ae7c0
		summarizeBy: none
		sourceColumn: MinuteKey

		annotation SummarizationSetBy = Automatic

	column FinQuarterKey
		dataType: string
		lineageTag: 4588dcd4-3398-4f2a-aee6-227e6116ac44
		summarizeBy: none
		sourceColumn: FinQuarterKey

		annotation SummarizationSetBy = Automatic

	column FinMonthKey
		dataType: string
		lineageTag: c011c0cc-4a22-40b2-8d5c-5bf1faba71dc
		summarizeBy: none
		sourceColumn: FinMonthKey

		annotation SummarizationSetBy = Automatic

	column IsCurrentYear
		dataType: string
		lineageTag: 940a2a6f-cc49-49ee-a4bd-92d97190fafb
		summarizeBy: none
		sourceColumn: IsCurrentYear

		annotation SummarizationSetBy = Automatic

	column IsCurrentMonth
		dataType: string
		lineageTag: a418aa16-3867-4f90-bddb-8fedd5aa6d0e
		summarizeBy: none
		sourceColumn: IsCurrentMonth

		annotation SummarizationSetBy = Automatic

	column IsCurrentWeek
		dataType: string
		lineageTag: 3c0878e4-e4bd-4904-90a7-fb59e4a6dd51
		summarizeBy: none
		sourceColumn: IsCurrentWeek

		annotation SummarizationSetBy = Automatic

	column IsCurrentFinYear
		dataType: string
		lineageTag: 196f9d3f-0728-47a2-a38e-8bc89aea90a7
		summarizeBy: none
		sourceColumn: IsCurrentFinYear

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: string
		lineageTag: edc752ff-e8f4-44b5-8c4a-a18e50d8cb85
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsToday
		dataType: string
		lineageTag: c29eb772-2d27-4050-80c3-b83ef80e70dd
		summarizeBy: none
		sourceColumn: IsToday

		annotation SummarizationSetBy = Automatic

	column IsTomorrow
		dataType: string
		lineageTag: acf4515f-28a6-4f81-94e7-96470c19bc7c
		summarizeBy: none
		sourceColumn: IsTomorrow

		annotation SummarizationSetBy = Automatic

	column IsYesterday
		dataType: string
		lineageTag: 745e081b-9289-4383-a679-f4d569a8b811
		summarizeBy: none
		sourceColumn: IsYesterday

		annotation SummarizationSetBy = Automatic

	partition Dim_times = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    today = Date.From(DateTime.LocalNow()),
				    start_date = #date(2015, 1, 1),
				    end_date = #date(2025, 12, 31)
				,
				    fin_year_first_half_months = {7, 8, 9, 10, 11, 12},
				    fin_year_second_half_months = {1, 2, 3, 4, 5, 6},
				    func_FinYear = (month_number, year) => if List.Contains(
				        fin_year_first_half_months,
				        month_number
				    ) then year + 1 else year,
				    Source = Table.TransformColumnTypes(
				        Table.FromList(
				            List.Generate(
				                () => [Value = Number.From(start_date), Index = 0], 
				                each [Value] <= Number.From(end_date),
				                each [Value = [Value] + (1 / 24), Index = [Index] + 1], 
				                each [Value]
				            ),
				            Splitter.SplitByNothing(),
				            {"Time"}
				        ),
				        {{"Time", type datetime}}
				    ),
				    #"Rounded Hour" = Table.TransformColumns(Source, {{"Time", each Time.StartOfHour(_), type datetime}}),
				    #"Added Custom" = Table.AddColumn(#"Rounded Hour", "Date", each Date.From([Time])),
				    #"Added Year" = Table.AddColumn(#"Added Custom", "Year", each Date.Year([Date])),
				    #"Added YearLabel" = Table.AddColumn(#"Added Year", "YearLabel", each "CY " & Text.From([Year])),
				    #"Added YearLabelShort" = Table.AddColumn(#"Added YearLabel", "YearLabelShort", each "CY " & Text.End(Text.From([Year]), 2)),
				    #"Added QuarterNumber" = Table.AddColumn(#"Added YearLabelShort", "QuarterNumber", each Date.QuarterOfYear([Date])),
				    #"Added QuarterLabel" = Table.AddColumn(#"Added QuarterNumber", "QuarterLabel", each "Quarter " & Text.From([QuarterNumber])),
				    #"Added QuarterLabelShort" = Table.AddColumn(#"Added QuarterLabel", "QuarterLabelShort", each "Q" & Text.From([QuarterNumber])),
				    #"Added QuarterYearLabel" = Table.AddColumn(#"Added QuarterLabelShort", "QuarterYearLabel", each [QuarterLabelShort] & ", CY " & Text.End(Text.From([Year]), 2)),
				    #"Added MonthNumber" = Table.AddColumn(#"Added QuarterYearLabel", "MonthNumber", each Date.Month([Date])),
				    #"Added MonthName" = Table.AddColumn(#"Added MonthNumber", "MonthName", each Date.MonthName([Date])),
				    #"Added MonthNameShort" = Table.AddColumn(#"Added MonthName", "MonthNameShort", each Text.Start([MonthName], 3)),
				    #"Added MonthYearLabel" = Table.AddColumn(#"Added MonthNameShort", "MonthYearLabel", each [MonthNameShort] & "-" & Text.End(Text.From([Year]), 2)),
				    #"Added WeekStart" = Table.AddColumn(#"Added MonthYearLabel", "WeekStart", each Date.StartOfWeek([Date])),
				    #"Added WeekStartLabel" = Table.AddColumn(#"Added WeekStart", "WeekStartLabel", each Date.ToText([WeekStart], "d-MMM-yy")),
				    #"Added WeekStartNumber" = Table.AddColumn(#"Added WeekStartLabel", "WeekStartNumber", each Date.WeekOfYear([WeekStart])),
				    #"Added WeekEnd" = Table.AddColumn(#"Added WeekStartNumber", "WeekEnd", each Date.EndOfWeek([Date])),
				    #"Added WeekEndLabel" = Table.AddColumn(#"Added WeekEnd", "WeekEndLabel", each Date.ToText([WeekEnd], "d-MMM-yy")),
				    #"Added WeekEndNumber" = Table.AddColumn(#"Added WeekEndLabel", "WeekEndNumber", each Date.WeekOfYear([WeekEnd])),
				    #"Added DayOfYearNumber" = Table.AddColumn(#"Added WeekEndNumber", "DayOfYearNumber", each Date.DayOfYear([Date])),
				    #"Added DayOfMonthNumber" = Table.AddColumn(#"Added DayOfYearNumber", "DayOfMonthNumber", each Date.Day([Date])),
				    #"Added WeekdayNumberMonSun" = Table.AddColumn(#"Added DayOfMonthNumber", "WeekdayNumberMonSun", each Date.DayOfWeek([Date], Day.Monday) + 1),
				    #"Added WeekdayNumberSunMon" = Table.AddColumn(#"Added WeekdayNumberMonSun", "WeekdayNumberSunMon", each Date.DayOfWeek([Date], Day.Sunday) + 1),
				    #"Added DateLabel" = Table.AddColumn(#"Added WeekdayNumberSunMon", "DateLabel", each Date.ToText([Date], "d-MMM-yy")),
				    #"Added WeekdayName" = Table.AddColumn(#"Added DateLabel", "WeekdayName", each Date.ToText([Date], "dddd")),
				    #"Added WeekdayNameShort" = Table.AddColumn(#"Added WeekdayName", "WeekdayNameShort", each Date.ToText([Date], "ddd")),
				    #"Added Hour" = Table.AddColumn(#"Added WeekdayNameShort", "Hour", each Time.Hour([Time])),
				    #"Added Minute" = Table.AddColumn(#"Added Hour", "Minute", each Time.Minute([Time])),
				    #"Added HourLabel" = Table.AddColumn(#"Added Minute", "HourLabel", each Number.ToText([Hour], "00") & ":00"),
				    #"Added MinuteLabel" = Table.AddColumn(#"Added HourLabel", "MinuteLabel", each Number.ToText([Minute], "00")),
				    #"Added HourMinuteLabel" = Table.AddColumn(#"Added MinuteLabel", "HourMinuteLabel", each Text.Start([HourLabel], 2) & ":" & [MinuteLabel]),
				    #"Added OperatingWindow" = Table.AddColumn(#"Added HourMinuteLabel", "OperatingWindow", each if List.Contains({23, 0, 1, 2, 3, 4, 5, 6}, [Hour])
				then "Overnight"
				else if List.Contains({7, 8, 9, 10, 11, 12, 13, 14}, [Hour]) then "Daytime"
				else "Evening"),
				    #"Added FinYear" = Table.AddColumn(#"Added OperatingWindow", "FinYear", each if List.Contains(
				    fin_year_first_half_months, 
				    [MonthNumber]
				) then [Year] + 1 
				else [Year]),
				    #"Added FinYearLabel" = Table.AddColumn(#"Added FinYear", "FinYearLabel", each "FY " & Text.From([FinYear])),
				    #"Added FinYearLabelShort" = Table.AddColumn(#"Added FinYearLabel", "FinYearLabelShort", each "FY " & Text.End(Text.From([FinYear]), 2)),
				    #"Added FinQuarterNumber" = Table.AddColumn(#"Added FinYearLabelShort", "FinQuarterNumber", each if List.Contains(
				    List.FirstN(fin_year_first_half_months, 3), 
				    [MonthNumber]
				) then 1 
				else if List.Contains(
				    List.LastN(fin_year_first_half_months, 3), 
				    [MonthNumber]
				) then 2 
				else if List.Contains(
				    List.FirstN(fin_year_second_half_months, 3), 
				    [MonthNumber]
				) then 3 
				else 4),
				    #"Added FinQuarterLabel" = Table.AddColumn(#"Added FinQuarterNumber", "FinQuarterLabel", each "Quarter " & Text.From([FinQuarterNumber])),
				    #"Added FinQuarterLabelShort" = Table.AddColumn(#"Added FinQuarterLabel", "FinQuarterLabelShort", each "Q" & Text.From([FinQuarterNumber])),
				    #"Added FinQuarterYearLabel" = Table.AddColumn(#"Added FinQuarterLabelShort", "FinQuarterYearLabel", each [FinQuarterLabelShort] & ", FY " & Text.End(Text.From([FinYear]), 2)),
				    #"Added MonthSequence (Temp)" = Table.AddColumn(#"Added FinQuarterYearLabel", "MonthSequence", each List.Repeat(
				    List.Combine(
				        {
				            fin_year_first_half_months, 
				            fin_year_second_half_months
				        }
				    ), 
				    2
				)),
				    #"Added FinMonthNumber" = Table.AddColumn(#"Added MonthSequence (Temp)", "FinMonthNumber", each [MonthSequence]{List.PositionOf(
				    [MonthSequence], 
				    [MonthNumber]
				) + 6}),
				    #"Removed MonthSequence (Temp)" = Table.RemoveColumns(#"Added FinMonthNumber",{"MonthSequence"}),
				    #"Added QuarterKey" = Table.AddColumn(#"Removed MonthSequence (Temp)", "QuarterKey", each Text.Combine(
				    {
				        Number.ToText([Year]), 
				        Number.ToText([QuarterNumber], "00")
				    }, 
				    ""
				)),
				    #"Added MonthKey" = Table.AddColumn(#"Added QuarterKey", "MonthKey", each Text.Combine(
				    {
				        Number.ToText([Year]),
				        Number.ToText([MonthNumber], "00")
				    }, 
				    ""
				)),
				    #"Added WeekStartKey" = Table.AddColumn(#"Added MonthKey", "WeekStartKey", each Date.ToText([WeekStart], "yyyyMMdd")),
				    #"Added WeekEndKey" = Table.AddColumn(#"Added WeekStartKey", "WeekEndKey", each Date.ToText([WeekEnd], "yyyyMMdd")),
				    #"Added DateKey" = Table.AddColumn(#"Added WeekEndKey", "DateKey", each Date.ToText([Date], "yyyyMMdd")),
				    #"Added HourKey" = Table.AddColumn(#"Added DateKey", "HourKey", each DateTime.ToText([Time], "yyyyMMddhh")),
				    #"Added MinuteKey" = Table.AddColumn(#"Added HourKey", "MinuteKey", each DateTime.ToText([Time], "yyyyMMddhhmm")),
				    #"Added FinQuarterKey" = Table.AddColumn(#"Added MinuteKey", "FinQuarterKey", each Text.Combine(
				    {
				        Number.ToText([FinYear]), 
				        Number.ToText([FinQuarterNumber], "00")
				    }, 
				    ""
				)),
				    #"Added FinMonthKey" = Table.AddColumn(#"Added FinQuarterKey", "FinMonthKey", each Text.Combine(
				    {
				        Number.ToText([FinYear]),
				        Number.ToText([FinMonthNumber], "00")
				    }, 
				    ""
				)),
				    #"Added IsCurrentYear" = Table.AddColumn(#"Added FinMonthKey", "IsCurrentYear", each if [Year] = Date.Year(today) then "Y" else "N"),
				    #"Added IsCurrentMonth" = Table.AddColumn(#"Added IsCurrentYear", "IsCurrentMonth", each if [MonthKey] = Date.ToText(today, "yyyyMM") then "Y" else "N"),
				    #"Added IsCurrentWeek" = Table.AddColumn(#"Added IsCurrentMonth", "IsCurrentWeek", each if [WeekStart] = Date.StartOfWeek(today) then "Y" else "N"),
				    #"Added IsCurrentFinYear" = Table.AddColumn(#"Added IsCurrentWeek", "IsCurrentFinYear", each if [FinYear] = func_FinYear([FinMonthNumber], [FinYear]) then "Y" else "N"),
				    #"Added IsWeekend" = Table.AddColumn(#"Added IsCurrentFinYear", "IsWeekend", each if [WeekdayNumberMonSun] >= 6 then "Y" else "N"),
				    #"Added IsToday" = Table.AddColumn(#"Added IsWeekend", "IsToday", each if [Date] = Date.From(DateTime.LocalNow()) then "Y" else "N"),
				    #"Added IsTomorrow" = Table.AddColumn(#"Added IsToday", "IsTomorrow", each if [Date] = Date.AddDays(today, 1) then "Y" else "N"),
				    #"Added IsYesterday" = Table.AddColumn(#"Added IsTomorrow", "IsYesterday", each if [Date] = Date.AddDays(today, -1) then "Y" else "N"),
				    #"Changed Data Types" = Table.TransformColumnTypes(#"Added IsYesterday",{{"Year", Int64.Type}, {"MonthNumber", Int64.Type}, {"DayOfYearNumber", Int64.Type}, {"FinQuarterNumber", Int64.Type}, {"FinMonthNumber", Int64.Type}, {"FinYear", Int64.Type}, {"WeekStartNumber", Int64.Type}, {"WeekEndNumber", Int64.Type}, {"WeekdayNumberMonSun", Int64.Type}, {"WeekdayNumberSunMon", Int64.Type}, {"QuarterNumber", Int64.Type}, {"YearLabel", type text}, {"YearLabelShort", type text}, {"QuarterLabel", type text}, {"QuarterLabelShort", type text}, {"QuarterYearLabel", type text}, {"MonthName", type text}, {"MonthNameShort", type text}, {"FinYearLabel", type text}, {"FinYearLabelShort", type text}, {"FinQuarterLabel", type text}, {"FinQuarterLabelShort", type text}, {"FinQuarterYearLabel", type text}, {"MonthYearLabel", type text}, {"WeekStart", type date}, {"WeekEnd", type date}, {"WeekStartLabel", type text}, {"WeekEndLabel", type text}, {"QuarterKey", type text}, {"MonthKey", type text}, {"WeekStartKey", type text}, {"WeekEndKey", type text}, {"FinQuarterKey", type text}, {"FinMonthKey", type text}, {"IsWeekend", type text}, {"IsToday", type text}, {"IsCurrentWeek", type text}, {"IsCurrentMonth", type text}, {"IsCurrentYear", type text}, {"IsCurrentFinYear", type text}, {"Date", type date}, {"Hour", Int64.Type}, {"Minute", Int64.Type}, {"HourLabel", type text}, {"MinuteLabel", type text}, {"HourMinuteLabel", type text}, {"HourKey", type text}, {"MinuteKey", type text}, {"IsTomorrow", type text}, {"IsYesterday", type text}, {"DateLabel", type text}, {"WeekdayName", type text}, {"WeekdayNameShort", type text}, {"DateKey", type text}, {"DayOfMonthNumber", Int64.Type}, {"OperatingWindow", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Data Types")
				in
				    #"Removed Duplicates"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

